using System.Collections.ObjectModel;

namespace Retro96.Plugins;

public enum PluginPermissionTier
{
    Standard,
    Elevated,
    Sensitive
}

public sealed record PluginPermissionInfo(
    PluginPermission Permission,
    string Name,
    string FriendlyName,
    PluginPermissionTier Tier,
    string Description,
    string Allows,
    string DoesNotAllow,
    string RiskNote,
    bool IsDataReading = false);

public static class PluginPermissionCatalog
{
    private static readonly IReadOnlyDictionary<PluginPermission, PluginPermissionInfo> Entries =
        Build();

    public static IReadOnlyList<PluginPermissionInfo> All { get; } =
        new ReadOnlyCollection<PluginPermissionInfo>(
            Enum.GetValues<PluginPermission>()
                .Where(p => p != PluginPermission.None)
                .Select(Get)
                .ToArray());

    public static PluginPermissionInfo Get(PluginPermission permission) =>
        Entries.TryGetValue(permission, out var value)
            ? value
            : throw new InvalidOperationException($"Missing permission metadata for {permission}.");

    public static bool IsSensitive(PluginPermission permission) => Get(permission).Tier == PluginPermissionTier.Sensitive;
    public static bool IsDataReading(PluginPermission permission) => Get(permission).IsDataReading;

    private static IReadOnlyDictionary<PluginPermission, PluginPermissionInfo> Build()
    {
        static PluginPermissionInfo I(PluginPermission permission, string friendly, PluginPermissionTier tier,
            string description, string allows, string denies, string risk, bool data = false) =>
            new(permission, PluginPermissionNames.ToNames(permission).Single(), friendly, tier, description, allows, denies, risk, data);

        return new Dictionary<PluginPermission, PluginPermissionInfo>
        {
            [PluginPermission.BrowserRead] = I(PluginPermission.BrowserRead, "Read browser state", PluginPermissionTier.Sensitive,
                "Reads the current page's browser-visible URL and title and other explicitly exposed browser state.",
                "Access to the read-only browser state exposed by the plugin API.",
                "It does not provide DOM nodes, script access, arbitrary page JavaScript, or filesystem paths.",
                "Page-related data may be sensitive, especially when combined with network access.", true),
            [PluginPermission.BrowserNavigation] = I(PluginPermission.BrowserNavigation, "Navigate the browser", PluginPermissionTier.Elevated,
                "Lets the plugin ask Retro96 to navigate the browser or open a window.",
                "User-visible navigation actions through the host browser API.",
                "It cannot silently control another browser or access live DOM objects.",
                "A plugin can change what page the browser displays."),
            [PluginPermission.BrowserWindows] = I(PluginPermission.BrowserWindows, "Open browser windows", PluginPermissionTier.Elevated,
                "Lets the plugin request a new Retro96 browser window for a URL.",
                "Creates a host-controlled browser window through the existing API.",
                "It does not expose arbitrary window handles or other application processes.",
                "The plugin can cause additional user-visible browser windows to open."),
            [PluginPermission.BrowserEvents] = I(PluginPermission.BrowserEvents, "Browser events", PluginPermissionTier.Standard,
                "Receives navigation, page-load, focus, and other browser lifecycle events exposed by the plugin contract.",
                "Receives the documented event fields, such as URL, title, focus, and progress metadata.",
                "Events do not contain page DOM, page script objects, or arbitrary content.",
                "Event data can reveal which pages are being used."),
            [PluginPermission.UserInterface] = I(PluginPermission.UserInterface, "Basic user interface", PluginPermissionTier.Standard,
                "Adds host-managed menu, toolbar, status, dialog, and panel UI using the plugin UI service.",
                "Creates the limited UI controls explicitly supported by Retro96.",
                "It does not create arbitrary native windows or draw over browser content.",
                "A plugin can add persistent UI that users may see while browsing."),
            [PluginPermission.Storage] = I(PluginPermission.Storage, "Plugin storage", PluginPermissionTier.Standard,
                "Reads and writes key/value data in the plugin's private data area.",
                "Stores plugin-owned settings and state within its sandbox data folder.",
                "It cannot read other plugins' data or paths outside its sandbox.",
                "Stored data stays available across plugin updates unless the plugin is removed."),
            [PluginPermission.Network] = I(PluginPermission.Network, "Network access", PluginPermissionTier.Elevated,
                "Allows outbound HTTP requests through the host network service.",
                "Makes host-brokered HTTP requests subject to Retro96's request, redirect, timeout, and response-size rules.",
                "It does not provide raw sockets, arbitrary protocols, or direct access to the browser's live network objects.",
                "Network access can transmit plugin-held data to a remote site."),
            [PluginPermission.FileSystem] = I(PluginPermission.FileSystem, "Plugin files", PluginPermissionTier.Elevated,
                "Reads and writes files only inside the plugin's private data directory.",
                "Uses the sandbox-relative file API for plugin-owned data.",
                "It cannot access arbitrary host filesystem paths outside that data directory.",
                "A compromised plugin can persist data inside its own sandbox."),
            [PluginPermission.Clipboard] = I(PluginPermission.Clipboard, "Clipboard", PluginPermissionTier.Elevated,
                "Reads or writes the system clipboard through the brokered clipboard API.",
                "Gets or sets text and image data exposed by the clipboard service.",
                "It does not expose clipboard history or arbitrary Win32 handles.",
                "Clipboard contents can contain user-entered private data.", true),
            [PluginPermission.BrowserZoom] = I(PluginPermission.BrowserZoom, "Browser zoom", PluginPermissionTier.Standard,
                "Reads or changes the browser's page zoom factor.",
                "Changes the active page zoom through the host browser API.",
                "It does not access page pixels or DOM objects solely through zoom control.",
                "A plugin can change the page's presentation."),
            [PluginPermission.BrowserCookies] = I(PluginPermission.BrowserCookies, "Browser cookies", PluginPermissionTier.Sensitive,
                "Reads and writes browser cookies through the brokered cookie service.",
                "Uses the documented cookie API and may set the Cookie header where explicitly allowed.",
                "It does not expose the full browser cookie database or cookie file paths.",
                "Cookies may contain login or tracking identifiers and should be treated as sensitive data.", true),
            [PluginPermission.BrowserFind] = I(PluginPermission.BrowserFind, "Find in page", PluginPermissionTier.Standard,
                "Uses the browser's built-in find feature on the current page.",
                "Starts, advances, or clears a normal browser find operation.",
                "It does not return arbitrary page text or DOM handles.",
                "The plugin controls a user-visible find operation."),
            [PluginPermission.BrowserScreenshot] = I(PluginPermission.BrowserScreenshot, "Page screenshot", PluginPermissionTier.Sensitive,
                "Captures the visible browser viewport as a PNG copy.",
                "Gets a copy of the current visible viewport image.",
                "It does not grant DOM handles or access to off-screen application windows.",
                "A screenshot can contain anything visible on the page, including private information.", true),
            [PluginPermission.UiPanel] = I(PluginPermission.UiPanel, "Plugin panels", PluginPermissionTier.Standard,
                "Creates and manages the plugin's host-side panel controls.",
                "Adds the limited panel widgets exposed by the plugin API.",
                "It does not grant arbitrary WinForms controls or native window access.",
                "A plugin can occupy visible UI space."),
            [PluginPermission.AudioPlayback] = I(PluginPermission.AudioPlayback, "Audio playback", PluginPermissionTier.Elevated,
                "Plays audio files through Retro96's host audio service.",
                "Uses the host's existing audio playback path.",
                "It does not provide direct audio-device access.",
                "A plugin can produce audible output."),
            [PluginPermission.Notifications] = I(PluginPermission.Notifications, "Notifications", PluginPermissionTier.Standard,
                "Shows Retro96 notifications and notification click actions.",
                "Creates host-managed notification messages.",
                "It does not create arbitrary system notification processes.",
                "Frequent notifications can interrupt the user's workflow."),
            [PluginPermission.Dialogs] = I(PluginPermission.Dialogs, "File dialogs", PluginPermissionTier.Elevated,
                "Shows brokered open/save dialogs for plugin sandbox files.",
                "Lets the user select or save sandbox-relative plugin data through host UI.",
                "It does not expose arbitrary filesystem paths to the plugin.",
                "The plugin can prompt the user for file-related actions."),
            [PluginPermission.EmbedRenderer] = I(PluginPermission.EmbedRenderer, "Embedded rendering", PluginPermissionTier.Elevated,
                "Renders plugin-owned embedded content as host-composited pixel buffers.",
                "Receives a bounded render request and returns a bounded frame buffer.",
                "It does not receive live page DOM nodes or draw directly into the host process UI.",
                "A plugin can render content inside matching embed elements."),
            [PluginPermission.EmbedNetwork] = I(PluginPermission.EmbedNetwork, "Embedded network", PluginPermissionTier.Elevated,
                "Opens host-brokered streams for embedded content.",
                "Uses the same host network restrictions rather than raw sockets.",
                "It does not get a raw socket or a browser-wide network interception hook.",
                "Embedded content can fetch remote data."),
            [PluginPermission.EmbedNavigate] = I(PluginPermission.EmbedNavigate, "Embedded navigation", PluginPermissionTier.Elevated,
                "Requests navigation initiated by an embedded plugin.",
                "Asks the host to navigate to a URL through normal navigation rules.",
                "It does not bypass the browser's navigation or security policy.",
                "An embed can request a visible page change."),
            [PluginPermission.EmbedStatus] = I(PluginPermission.EmbedStatus, "Embedded status", PluginPermissionTier.Standard,
                "Sets the host status text for an embedded plugin.",
                "Updates the browser's plugin-owned status display.",
                "It does not write arbitrary browser chrome or application state.",
                "A plugin can influence the status text shown to users."),
            [PluginPermission.EmbedPrint] = I(PluginPermission.EmbedPrint, "Embedded printing", PluginPermissionTier.Elevated,
                "Allows the host to request print rendering for an embedded plugin.",
                "Produces a bounded host-composited print frame.",
                "It does not directly control printer devices or files.",
                "Printing can cause user-visible document output."),
            [PluginPermission.EmbedScript] = I(PluginPermission.EmbedScript, "Embedded page calls", PluginPermissionTier.Elevated,
                "Publishes a named, typed method surface for the page's embedded plugin bridge.",
                "Exposes only named methods and flat primitive arguments/results across the embed bridge.",
                "It does not provide arbitrary script injection, live DOM handles, or arbitrary JavaScript execution.",
                "Even typed page calls can trigger page-visible behavior."),
            [PluginPermission.PageRead] = I(PluginPermission.PageRead, "Read page content", PluginPermissionTier.Sensitive,
                "Reads capped plain text, links, or current selection from the active page.",
                "Gets copied strings and link records with host-enforced size and count caps.",
                "It does not receive DOM nodes, script objects, layout boxes, or arbitrary page JavaScript.",
                "Page text and links may contain private or sensitive browsing data, especially with network access.", true),
            [PluginPermission.NetworkRules] = I(PluginPermission.NetworkRules, "Network rules", PluginPermissionTier.Elevated,
                "Submits declarative block, redirect, and strip-header rules for host-side request handling.",
                "Lets the host evaluate safe declarative rules without exposing browser requests to the plugin.",
                "It does not see live requests or raw sockets and cannot create a per-host network allowlist.",
                "Rules can change how browser requests are sent or blocked."),
            [PluginPermission.Protocol] = I(PluginPermission.Protocol, "Custom protocols", PluginPermissionTier.Elevated,
                "Registers a URL scheme whose responses are returned as bounded bytes and a content type.",
                "Supplies host-parsed content for schemes registered by the plugin.",
                "It does not write directly into the renderer or return a live document object.",
                "Protocol output is untrusted and is parsed by the normal host renderer."),
            [PluginPermission.ContentTransform] = I(PluginPermission.ContentTransform, "Content transforms", PluginPermissionTier.Sensitive,
                "This plugin can read and change the pages you visit.",
                "Receives only responses matching the manifest's declared URL and MIME patterns and returns HTML for the host parser after script, on* attributes, and javascript: URLs are stripped.",
                "It does not receive non-matching responses, DOM nodes, live requests, or direct renderer objects.",
                "This permission exposes page response data and can alter rendered content; with network access, the plugin could send that data to any site.", true),
            [PluginPermission.PageStyle] = I(PluginPermission.PageStyle, "Page styles", PluginPermissionTier.Elevated,
                "Adds host-sanitized CSS to pages without script access.",
                "Injects CSS after removing external references and url() constructs.",
                "It does not allow JavaScript or external stylesheet loads through the plugin style path.",
                "Unsafe CSS can still change page presentation, so the host strips data-exfiltration primitives."),
            [PluginPermission.Tabs] = I(PluginPermission.Tabs, "Tab access", PluginPermissionTier.Sensitive,
                "Lists tab URL/title summaries and can participate in BeforeNavigate decisions.",
                "Gets only URL/title tab summaries and a time-limited navigation decision callback.",
                "It does not receive page content or arbitrary window handles.",
                "Tab URLs and titles can reveal browsing activity; network access can transmit that data.", true),
            [PluginPermission.History] = I(PluginPermission.History, "History", PluginPermissionTier.Sensitive,
                "Reads a capped history list with limited title, URL, and visit-time fields.",
                "Gets only the host-capped history fields and result count.",
                "It does not access the underlying history database or unrelated application files.",
                "History reveals browsing activity and every plugin read is recorded in the activity log.", true),
            [PluginPermission.Bookmarks] = I(PluginPermission.Bookmarks, "Bookmarks", PluginPermissionTier.Sensitive,
                "Reads or changes the browser's bookmarks through the host service.",
                "Uses the limited bookmark record and mutation API.",
                "It does not access bookmark storage files directly or arbitrary browser databases.",
                "Bookmarks reveal user interests and can be modified by the plugin; network access can transmit read data.", true),
            [PluginPermission.Downloads] = I(PluginPermission.Downloads, "Downloads", PluginPermissionTier.Elevated,
                "Starts a host-validated download into the plugin's sandbox data directory and receives progress.",
                "Uses HTTP/HTTPS, host URL validation, a size cap, and a user confirmation.",
                "It does not write outside the plugin sandbox or access raw sockets.",
                "Downloads consume network and storage resources and can persist untrusted content."),
            [PluginPermission.Omnibox] = I(PluginPermission.Omnibox, "Omnibox keywords", PluginPermissionTier.Standard,
                "Registers a keyword for text-only address-bar suggestions.",
                "Returns bounded text suggestions while the host handles selection and navigation.",
                "It does not see arbitrary page content or directly control address-bar rendering.",
                "A keyword plugin can influence what users see while typing in the address bar."),
            [PluginPermission.Settings] = I(PluginPermission.Settings, "Plugin settings", PluginPermissionTier.Standard,
                "Defines host-rendered plugin preferences that are stored through the plugin storage service.",
                "Creates bounded toggle, text, and select settings in Preferences.",
                "It does not get access to unrelated Retro96 settings or native preference files.",
                "Settings can change plugin behavior but remain host-rendered controls."),
            [PluginPermission.UiExtras] = I(PluginPermission.UiExtras, "UI extras", PluginPermissionTier.Standard,
                "Adds limited icons, badges, menu placement, and host-registered keyboard shortcuts.",
                "Uses host-controlled toolbar/menu surfaces and rejects shortcut conflicts.",
                "It does not create arbitrary native controls or override built-in shortcuts.",
                "Extra UI can affect what commands users notice and invoke."),
            [PluginPermission.EmbedAudio] = I(PluginPermission.EmbedAudio, "Embedded PCM audio", PluginPermissionTier.Elevated,
                "Pushes bounded PCM audio samples to the host embed mixer.",
                "Queues validated PCM samples for host mixing with per-embed mute and interaction gating.",
                "It does not access the system audio device directly.",
                "An embed can produce audible output once host interaction unmutes it."),
            [PluginPermission.EmbedExtras] = I(PluginPermission.EmbedExtras, "Embedded host extras", PluginPermissionTier.Standard,
                "Uses fixed cursor choices and receives embed visibility, pause, and resize notifications.",
                "Exposes only the fixed embed lifecycle and cursor data in the contract.",
                "It does not access arbitrary window handles, files, or page DOM nodes.",
                "Embed lifecycle information can change plugin presentation behavior.")
        };
    }
}
